export enum StringValueEnum {
    Error="Error",
    EnableYourGPS="Problem to get current location, please retry or enable your GPS ...",
    Loading="Loading...",
    UnknownError="Unknown Error",
    NotFound="Not Found",
    PleaseCheckNetworkConnection="Please check network connection...",
    LocationNotFound="Location not found...",
    Highest="Highest",
    Lowest="Lowest",
    PleaseEnterMoreThanTwoCharacters="Please enter more than 2 characters",
    URLForcast="http://api.openweathermap.org/data/2.5/forecast?q=",
    URLCurrent="http://api.openweathermap.org/data/2.5//weather?q=",
    AppID="d994b85acc1528b1a51fb0273b7ca7c4",
    WEATHERICONURL="http://openweathermap.org/img/w/",
}
